version: "2"
services:
  web:
    container_name: web
    restart: always
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    command:
      npm run dev
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
volumes:
  data: